### PR TITLE
Readability

### PR DESCRIPTION
**Pull request by NazarShuk**
More comments heck yeah, also renamed the shortened variable names because I just can't.

### CODE REVIEW

**Review by alexandros3015 — CHANGES_REQUESTED** [review]
Update it to the latest version I will not make changes

**Comment by NazarShuk** [comment]
Did I forget to pull?

**Comment by alexandros3015** [comment]
idk

**Comment by alexandros3015** [comment]
Just like make sure no issues with the current version and I'll do it

**Comment by NazarShuk** [comment]
Oki doki

**Pull request closed without merging**
